#!/usr/bin/env bash

# blackboard - the simple logger
#
# GNU General Public License v3.0 
#
# Copyright (c) 2021 Advait Raykar
# Personal Page: https//advait.live


RED='\033[0;31m'
GREEN='\x1b[1;32m'
NC='\033[0m'

if [ ! -d ~/.blackboard ]; then
  	echo "Blackboard folder doesn't exits, creating logger folder under ~/.blackboard"
	mkdir -p ~/.blackboard;
fi


# Adds the log in the format "Date, Activity, Time"
function add_log {

	for opt in "$@"
	do
		case $opt in
	    		-sat)
				echo "$(date +%F)", "$2", "$3", "satisfying" >> ~/.blackboard/timelog.txt
	      			exit
				;;
	    		-unsat)
				echo "$(date +%F)", "$2", "$3", "unsatisfying" >> ~/.blackboard/timelog.txt
	      			exit
				;;
	    		-indiff)
				echo "$(date +%F)", "$2", "$3", "indifferent" >> ~/.blackboard/timelog.txt
	      			exit
				;;
	  	esac
	done

	echo -e "${RED}You need to enter what you feel about the task.${NC}\n -unsat for unsatisfying  \n -sat for satisfying \n -indiff for indifferent"
}

function show_logs {
	cat ~/.blackboard/timelog.txt | column -s, -t | less -#2 -N -S
}

green_echo() {
    echo -e "${GREEN}$1${NC}"
}

print_logo() {
	echo "      ____  _               _____ _  ______   ____          _____  _____      ";
	echo "     |  _ \| |        /\   / ____| |/ /  _ \ / __ \   /\   |  __ \|  __ \     ";
	echo "     | |_) | |       /  \ | |    | ' /| |_) | |  | | /  \  | |__) | |  | |    ";
	echo "     |  _ <| |      / /\ \| |    |  < |  _ <| |  | |/ /\ \ |  _  /| |  | |    ";
	echo "     | |_) | |____ / ____ \ |____| . \| |_) | |__| / ____ \| | \ \| |__| |    ";
	echo "  _  |____/|______/_/  _ \_\_____|_|\_\____/ \____/_/    \_\_|  \_\_____/     ";
	echo " | | | |              (_)               | |    | |                            ";
	echo " | |_| |__   ___   ___ _ _ __ ___  _ __ | | ___| | ___   __ _  __ _  ___ _ __ ";
	echo " | __| '_ \ / _ \ / __| | '_ \` _ \| '_ \| |/ _ \ |/ _ \ / _\` |/ _\` |/ _ \ '__|";
	echo " | |_| | | |  __/ \__ \ | | | | | | |_) | |  __/ | (_) | (_| | (_| |  __/ |   ";
	echo "  \__|_| |_|\___| |___/_|_| |_| |_| .__/|_|\___|_|\___/ \__, |\__, |\___|_|   ";
	echo "                                  | |                    __/ | __/ |          ";
	echo "                                  |_|                   |___/ |___/           ";

}

if [ "$1" == "" ]; then
	
	print_logo

	echo -e "\n\n\t--add or -a : To add an entry, run with '-a <activity> <timespent>'. Example:"
	green_echo "\t\tbb -a 'saw movie' 2h"
	echo -e "\n\t--show or -s: To see all the logs, run with '-s'. Example:"
	green_echo "\t\tbb -s"

fi
if [ "$1" == "-a" -o "$1" == "--add" ]; then
	add_log "$@"
fi
if [ "$1" == "-s" -o "$1" == "--show" ]; then
	show_logs
fi

